version: '3.7'
services:
  mongo:
    image: mongo:5.0.15
    privileged: true
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    ports:
      - 27019:27019
      - 27017:27017
    environment:
      TZ: "Asia/Jakarta"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: strongpassword
    volumes:
      - ./data-db:/data/db
      - ./config:/etc/mongo
      - ./configdb:/data/configdb

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      TZ: "Asia/Jakarta"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: strongpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:strongpassword@mongo:27017/