version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: '!n!pr1v4t3!'
       MYSQL_DATABASE: 'wordpress'
       MYSQL_USER: 'thermindo'
       MYSQL_PASSWORD: 'Th3rm1nd012!@'
       TZ: "Asia/Jakarta"

   wordpress:
     depends_on:
       - db
     image: wordpress:php7.2
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: 'db:3306'
       WORDPRESS_DB_USER: 'thermindo'
       WORDPRESS_DB_PASSWORD: 'Th3rm1nd012!@'
       WORDPRESS_DB_NAME: 'wordpress'
       TZ: "Asia/Jakarta"
     volumes:
       - "./web:/var/www/html"

   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     links:
       - 'db:db'
     ports:
       - 8080:80
     environment:
       TZ: "Asia/Jakarta"

volumes:
    db_data: {}

