version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    command: sh -c "echo 'JAVA_ARGS="$JAVA_ARGS -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true" > /etc/default/jenkins'
    privileged: true
    container_name: jenkins
    hostname: jenkins
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      TZ: "Asia/Jakarta"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock