version: '3.8'
services:

  erp:
    image: odoo:12.0
    environment:
    - TZ=Asia/Jakarta
    - HOST=pg
    - USER=odoo
    - PASSWORD=odoo
    depends_on:
      - pg
    hostname: 'odoo'
    container_name: 'odoo'
    ports:
      - '8069:8069'
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons/extra:/mnt/extra-addons
      - ./addons/default:/usr/lib/python2.7/dist-packages/odoo/addons/
  pg:
    image: postgres:10
    environment:
      - TZ=Asia/Jakarta
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    hostname: 'pg'
    container_name: 'pg'
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data: