name: Alpine with Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build_and_push_image:
    name: Build, Tag and Push Image to Docker Hub
    runs-on: ubuntu-latest
    steps:

    - name: Git Checkout
      uses: actions/checkout@v3

    - name: Docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build, Tag, Push the Docker image
      run: |
        IMAGE_TAG=$(echo $GITHUB_SHA | cut -c 1-7)
        docker build . --file dockerfiles/custom-distro/alpine-docker.dockerfile -t ${{secrets.DOCKER_USER}}/alpine-docker:latest
        docker push ${{secrets.DOCKER_USER}}/alpine-docker:latest
        docker tag ${{secrets.DOCKER_USER}}/alpine-docker:latest ${{secrets.DOCKER_USER}}/alpine-docker:$IMAGE_TAG
        docker push ${{secrets.DOCKER_USER}}/alpine-docker:$IMAGE_TAG

    - name: Docker logout
      run: |
        docker logout
