name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build the Docker image
      run: |
        pwd
        docker build dockerfiles/remote_storage_adapter/. --file Dockerfile -t suryastef/remote_storage_adapter:$(date +%s) -t suryastef/remote_storage_adapter:latest

    - name: Push image to Docker Hub
      run: docker push ${{secrets.DOCKER_USER}}/remote_storage_adapter