name: Remote Storage Adapter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_push_image:
    name: Build, Tag and Push Image to Docker Hub
    runs-on: ubuntu-latest
    steps:

    - name: Git Checkout
      uses: actions/checkout@v3

    - name: Docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build, Tag, Push the Docker image
      run: |
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)
        docker build . --file dockerfiles/remote_storage_adapter/Dockerfile -t ${{secrets.DOCKER_USER}}/remote_storage_adapter:$IMAGE_TAG
        docker push ${{secrets.DOCKER_USER}}/remote_storage_adapter:$IMAGE_TAG

    - name: Docker logout
      run: |
        docker logout
